name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'app/frontend/**'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        working-directory: app/frontend
        run: |
          npm install
          npm install -g @capacitor/cli

      - name: Build web app
        working-directory: app/frontend
        run: npm run build

      - name: Setup Android
        working-directory: app/frontend
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Build APK
        working-directory: app/frontend/android
        run: |
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: synerchat-android
          path: app/frontend/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

      - name: Copy APK to downloads
        run: |
          mkdir -p app/backend/downloads
          cp app/frontend/android/app/build/outputs/apk/debug/app-debug.apk app/backend/downloads/synerchat.apk

      - name: Commit APK
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add app/backend/downloads/synerchat.apk
          git commit -m "Update Android APK [skip ci]" || echo "No changes"
          git push || echo "Nothing to push"
